# Generated by Django 5.2.4 on 2026-03-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pachet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('pro', 'Pro')], max_length=20)),
                ('pret_lunar', models.DecimalField(decimal_places=2, help_text='Preț lunar în EUR', max_digits=8)),
                ('pret_setup', models.DecimalField(decimal_places=2, default=0, help_text='Cost setup o singură dată, în EUR', max_digits=8)),
                ('descriere', models.TextField(help_text='1-2 propoziții scurte despre pachet')),
                ('features', models.JSONField(default=list, help_text='Listă de string-uri — bullet points afișate pe card')),
                ('recomandat', models.BooleanField(default=False, help_text='Cardul evidențiat cu border auriu')),
                ('activ', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine afișare (crescător)')),
            ],
            options={
                'verbose_name': 'Pachet',
                'verbose_name_plural': 'Pachete',
                'ordering': ['ordine'],
            },
        ),
    ]
