# Generated by Django 5.1.4 on 2026-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudiuDeCaz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titlu", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("client", models.CharField(max_length=100)),
                (
                    "industrie",
                    models.CharField(
                        choices=[
                            ("transport", "Transport & Logistică"),
                            ("fmcg", "FMCG / Alimentar"),
                            ("retail", "Retail"),
                            ("servicii", "Servicii"),
                            ("alt", "Altele"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Ads"),
                            ("google", "Google Ads"),
                            ("tiktok", "TikTok Ads"),
                            ("web", "Web Development"),
                            ("mix", "Mix canale"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "descriere_scurta",
                    models.CharField(
                        help_text="Apare în card pe pagina de listing", max_length=300
                    ),
                ),
                ("descriere_completa", models.TextField()),
                ("obiectiv", models.TextField(help_text="Ce și-a propus clientul")),
                ("solutie", models.TextField(help_text="Ce am implementat")),
                (
                    "rezultate",
                    models.TextField(help_text="Cifre și rezultate concrete"),
                ),
                (
                    "imagine_cover",
                    models.ImageField(blank=True, upload_to="studii/covers/"),
                ),
                (
                    "imagine_rezultate",
                    models.ImageField(blank=True, upload_to="studii/results/"),
                ),
                ("data_proiect", models.DateField()),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Afișat pe homepage"),
                ),
                ("activ", models.BooleanField(default=True)),
                ("creat_la", models.DateTimeField(auto_now_add=True)),
                (
                    "metrica_1_label",
                    models.CharField(
                        blank=True, help_text="Ex: Total Impressions", max_length=50
                    ),
                ),
                (
                    "metrica_1_valoare",
                    models.CharField(blank=True, help_text="Ex: 400K+", max_length=50),
                ),
                ("metrica_2_label", models.CharField(blank=True, max_length=50)),
                ("metrica_2_valoare", models.CharField(blank=True, max_length=50)),
                ("metrica_3_label", models.CharField(blank=True, max_length=50)),
                ("metrica_3_valoare", models.CharField(blank=True, max_length=50)),
                ("metrica_4_label", models.CharField(blank=True, max_length=50)),
                ("metrica_4_valoare", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Studiu de caz",
                "verbose_name_plural": "Studii de caz",
                "ordering": ["-featured", "-data_proiect"],
            },
        ),
    ]
