# Generated by Django 5.2.4 on 2026-03-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studii_de_caz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiudecaz',
            name='logo_client',
            field=models.ImageField(blank=True, null=True, upload_to='studii/logos/'),
        ),
        migrations.AddField(
            model_name='studiudecaz',
            name='nisa',
            field=models.CharField(blank=True, help_text='Ex: Transport persoane — Diaspora România–Germania', max_length=200),
        ),
        migrations.AddField(
            model_name='studiudecaz',
            name='perioada',
            field=models.CharField(blank=True, help_text='Ex: Ianuarie 2026 – prezent', max_length=100),
        ),
        migrations.AddField(
            model_name='studiudecaz',
            name='problema',
            field=models.TextField(blank=True, help_text='Problema pe care a avut-o clientul'),
        ),
    ]
