# Generated by Django 5.1.4 on 2026-03-05 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tranzactie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_tranzactie", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("bt_order_id", models.CharField(blank=True, max_length=100)),
                ("bt_response_code", models.CharField(blank=True, max_length=20)),
                ("suma", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(default="RON", max_length=3)),
                ("descriere_serviciu", models.CharField(max_length=200)),
                ("nume_client", models.CharField(max_length=100)),
                ("email_client", models.EmailField(max_length=254)),
                ("telefon_client", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "În așteptare"),
                            ("completed", "Finalizată"),
                            ("failed", "Eșuată"),
                            ("refunded", "Rambursată"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("creat_la", models.DateTimeField(auto_now_add=True)),
                ("actualizat_la", models.DateTimeField(auto_now=True)),
                ("raspuns_complet_bt", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Tranzacție",
                "verbose_name_plural": "Tranzacții",
                "ordering": ["-creat_la"],
            },
        ),
    ]
