# Generated by Django 5.2.4 on 2026-03-16 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plati', '0001_initial'),
        ('servicii', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('activ', 'Activ'), ('anulat', 'Anulat'), ('suspendat', 'Suspendat'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('data_start', models.DateTimeField()),
                ('data_urmatoarei_plati', models.DateTimeField(blank=True, null=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('pachet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonamente', to='servicii.pachet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonamente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonament',
                'verbose_name_plural': 'Abonamente',
                'ordering': ['-creat_la'],
            },
        ),
        migrations.CreateModel(
            name='LivrabilClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('reclame', 'Reclame'), ('rapoarte', 'Rapoarte'), ('documente', 'Documente'), ('altele', 'Altele')], default='altele', max_length=20)),
                ('fisier', models.FileField(upload_to='livrabile/')),
                ('descriere', models.TextField(blank=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('abonament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrabile', to='plati.abonament')),
            ],
            options={
                'verbose_name': 'Livrabil client',
                'verbose_name_plural': 'Livrabile clienți',
                'ordering': ['-creat_la'],
            },
        ),
        migrations.CreateModel(
            name='Plata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valuta', models.CharField(default='eur', max_length=3)),
                ('status', models.CharField(choices=[('reusit', 'Reușit'), ('esuat', 'Eșuat'), ('pending', 'În așteptare')], default='pending', max_length=20)),
                ('data_plata', models.DateTimeField()),
                ('factura_url', models.URLField(blank=True, help_text='Link factură din Stripe')),
                ('abonament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plati', to='plati.abonament')),
            ],
            options={
                'verbose_name': 'Plată',
                'verbose_name_plural': 'Plăți',
                'ordering': ['-data_plata'],
            },
        ),
        migrations.CreateModel(
            name='RaportClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(help_text='Ex: Raport Mai 2026', max_length=200)),
                ('luna', models.DateField(help_text='Prima zi a lunii de raportare')),
                ('fisier', models.FileField(upload_to='rapoarte/')),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('abonament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapoarte', to='plati.abonament')),
            ],
            options={
                'verbose_name': 'Raport client',
                'verbose_name_plural': 'Rapoarte clienți',
                'ordering': ['-luna'],
            },
        ),
    ]
