# Generated by Django 5.2.4 on 2026-03-16 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plati', '0002_abonament_livrabilclient_plata_raportclient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('telefon_client', models.CharField(blank=True, max_length=20)),
                ('nisa_client', models.CharField(blank=True, help_text='Domeniu/industrie client', max_length=200)),
                ('pachet_dorit_dupa_trial', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('pro', 'Pro'), ('nedecis', 'Încă nedecis')], default='nedecis', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('suma', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('valuta', models.CharField(default='eur', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'În așteptare plată'), ('activ', 'Activ'), ('expirat', 'Expirat'), ('convertit', 'Convertit la pachet'), ('refundat', 'Rambursat')], default='pending', max_length=20)),
                ('data_start', models.DateTimeField(blank=True, null=True)),
                ('data_expirare', models.DateTimeField(blank=True, null=True)),
                ('convertit_la_pachet', models.BooleanField(default=False)),
                ('nota_interna', models.TextField(blank=True, help_text='Note interne (nu se afișează clientului)')),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Trial 7 Zile',
                'verbose_name_plural': 'Promo Trials',
                'ordering': ['-creat_la'],
            },
        ),
    ]
