# Generated by Django 5.2.4 on 2026-03-17 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plati', '0003_promo_trial'),
        ('servicii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSemnat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contract', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_nume_complet', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_telefon', models.CharField(blank=True, max_length=20)),
                ('client_firma', models.CharField(blank=True, help_text='Numele firmei (opțional PFA/SRL)', max_length=200)),
                ('client_cui', models.CharField(blank=True, help_text='CUI / CNP (opțional)', max_length=20)),
                ('client_adresa', models.TextField(blank=True)),
                ('semnatura_text', models.CharField(help_text='Numele tastat de client ca semnătură', max_length=150)),
                ('ip_semnare', models.GenericIPAddressField(blank=True, null=True)),
                ('data_semnare', models.DateTimeField(auto_now_add=True)),
                ('pachet_snapshot', models.JSONField(default=dict, help_text='Datele pachetului la momentul semnării')),
                ('status', models.CharField(choices=[('semnat', 'Semnat'), ('platit', 'Plătit'), ('anulat', 'Anulat')], default='semnat', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('pachet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracte', to='servicii.pachet')),
            ],
            options={
                'verbose_name': 'Contract Semnat',
                'verbose_name_plural': 'Contracte Semnate',
                'ordering': ['-data_semnare'],
            },
        ),
    ]
