# Generated by Django 5.1.4 on 2026-03-05 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("descriere", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categorii",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Articol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titlu", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "rezumat",
                    models.CharField(
                        help_text="Apare în listing și meta description", max_length=300
                    ),
                ),
                ("continut", models.TextField()),
                (
                    "imagine_cover",
                    models.ImageField(blank=True, upload_to="blog/covers/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("publicat", "Publicat")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "data_publicare",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("creat_la", models.DateTimeField(auto_now_add=True)),
                ("actualizat_la", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "categorie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articole",
                        to="blog.categorie",
                    ),
                ),
                ("taguri", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "verbose_name_plural": "Articole",
                "ordering": ["-data_publicare"],
            },
        ),
    ]
